'use client';
import React from 'react';
import DashboardHeader from '../DashboardHeader';
import { SearchIcon } from '@/components/icons';
import NewOperationsModal from './NewOperationsModal';
import OperationsTable from './OperationsTable';
import { Input, Select, SelectItem } from '@heroui/react';

const OperationsDashboard = () => {
  const statuses = [
    { key: 'all', label: 'All' },
    { key: 'completed', label: 'Completed' },
    { key: 'in-progress', label: 'In Progress' },
    { key: 'inspection', label: 'Inspection' },
  ];
  const phases = [
    { key: 'all', label: 'All' },
    { key: 'planning', label: 'Planning' },
    { key: 'design', label: 'Design' },
    { key: 'execution', label: 'Execution' },
    { key: 'closure', label: 'Closure' },
  ];
  const locations = [
    { key: 'all', label: 'All' },
    { key: 'abuja', label: 'Abuja' },
    { key: 'ibadan', label: 'Ibadan' },
    { key: 'lagos', label: 'Lagos' },
  ];

  return (
    <section className="bg-white dark:bg-black dark:p-0 p-4 rounded-lg flex flex-col gap-4">
      <div className="flex flex-col sm:flex-row justify-between items-start">
        <div>
          <DashboardHeader
            title="All Operations"
            description="Track revenue generated by different services over time."
          />
        </div>
        <div>
          <Input
            label="Search for operations"
            labelPlacement="outside"
            placeholder="Clients, location, progress etc"
            startContent={
              <SearchIcon className="text-2xl size-4 text-default-400 pointer-events-none shrink-0" />
            }
            type="text"
          />
        </div>
      </div>
      <div className="flex items-center sm:justify-between flex-wrap gap-4">
        <div className="w-[750px] grid sm:grid-cols-4 grid-cols-1 items-center gap-4">
          <div className="w-full">10 results found</div>
          <Select
            className="max-w-xs"
            // label="Filter by Status"
            placeholder="Select status"
            defaultSelectedKeys={['all']}
            items={statuses}
            startContent={'Status:'}
          >
            {(status) => (
              <SelectItem key={status.key}>{status.label}</SelectItem>
            )}
          </Select>
          <Select
            className="max-w-xs"
            // label="Filter by Status"
            placeholder="Select stage"
            defaultSelectedKeys={['all']}
            items={phases}
            startContent={'Phase:'}
          >
            {(stage) => <SelectItem key={stage.key}>{stage.label}</SelectItem>}
          </Select>
          <Select
            className="max-w-xs"
            defaultSelectedKeys={['all']}
            items={locations}
            startContent={'Location:'}
          >
            {(city) => <SelectItem key={city.key}>{city.label}</SelectItem>}
          </Select>
        </div>
        <NewOperationsModal />
      </div>

      {/* Operations table  */}
      <OperationsTable />
    </section>
  );
};

export default OperationsDashboard;
