'use client';
import React, { useCallback } from 'react';
import DashboardHeader from '../DashboardHeader';
import { SearchIcon } from '@/components/icons';
import NewOperationsModal from '../Forms/Project/CreateProjectForm';
import OperationsTable from './OperationsTable';
import { Button, ButtonGroup, Input, Select, SelectItem } from '@heroui/react';
import useDebounce from '@/hooks/useDebounceHook';
import { useGetAllProjectsQuery } from '@/lib/services/projects/projects.api';
import { Project } from '@/types/projects.types';
import { useSession } from 'next-auth/react';
import CreateProjectForm from '../Forms/Project/CreateProjectForm';

const rowsPerPage = 10;
const OperationsDashboard = () => {
  const { data: session } = useSession();
  const statuses = [
    { key: '', label: 'All' },
    { key: '100', label: 'Completed' },
  ];
  const phases = [
    { key: '', label: 'All' },
    { key: 'planning', label: 'Planning' },
    { key: 'design', label: 'Design' },
    { key: 'execution', label: 'Execution' },
    { key: 'inspection', label: 'Inspection' },
    { key: 'closure', label: 'Closure' },
  ];
  const locations = [
    { key: '', label: 'All' },
    { key: 'abuja', label: 'Abuja' },
    { key: 'ibadan', label: 'Ibadan' },
    { key: 'lagos', label: 'Lagos' },
  ];

  const [page, setPage] = React.useState<number>(1);

  const [search, setSearch] = React.useState<string>('');
  const debouncedSearch = useDebounce(search, 500);

  const [statusFilter, setStatusFilter] = React.useState<string>('');
  const [phaseFilter, setPhaseFilter] = React.useState<string>('');
  const [locationFilter, setLocationFilter] = React.useState<string>('');

  const [sortBy, setSortBy] = React.useState<string>('createdAt');
  const [sortOrder, setSortOrder] = React.useState<'asc' | 'desc'>('desc');

  const [operationsTab, setOperationsTab] = React.useState<'owner' | ''>('');

  const OPERATIONS_TABS: {
    label: string;
    value: 'owner' | '';
  }[] = [
    { label: 'My Projects', value: 'owner' },
    { label: 'General', value: '' },
  ];

  const { data, isLoading } = useGetAllProjectsQuery({
    page,
    limit: rowsPerPage,
    search: debouncedSearch,
    status: statusFilter ? statusFilter : undefined,
    phase: phaseFilter ? phaseFilter : undefined,
    state: locationFilter,
    assignedTo: operationsTab === 'owner' ? session?.user?.id : '',
    sortBy,
    sortOrder,
  });

  const projects: Project[] = data?.data ?? [];
  const totalPages = data?.pagination?.totalPages ?? 1;

  console.log('projects:', projects);

  const handleSort = useCallback(
    (column: string) => {
      if (sortBy === column) {
        setSortOrder((prev) => (prev === 'asc' ? 'desc' : 'asc'));
      } else {
        setSortBy(column);
        setSortOrder('asc');
      }
    },
    [sortBy, sortOrder]
  );

  // 🔥 Reset page when OPERATIONS_TABS/search change
  React.useEffect(() => {
    setPage(1);
  }, [debouncedSearch, statusFilter, phaseFilter, sortBy, sortOrder]);

  return (
    <section className="bg-white dark:bg-black dark:p-0 p-4 rounded-lg flex flex-col gap-4">
      <div className="flex flex-col sm:flex-row justify-between items-start">
        <div>
          <DashboardHeader
            title="All Operations"
            description="Track revenue generated by different services over time."
          />
        </div>
        <div>
          <Input
            label="Search for operations"
            labelPlacement="outside"
            placeholder="Search by name, email, client..."
            startContent={
              <SearchIcon className="text-2xl size-4 text-default-400 pointer-events-none shrink-0" />
            }
            type="text"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>
      </div>
      <div className="flex items-center sm:justify-between flex-wrap gap-4">
        <div className="w-[830px] grid sm:grid-cols-4 grid-cols-1 items-center gap-4">
          <Select
            className="sm:max-w-xs w-full"
            placeholder="Select status"
            defaultSelectedKeys={['all']}
            // items={statuses}
            selectedKeys={[statusFilter]}
            startContent={'Status:'}
            onChange={(e) => setStatusFilter(e.target.value)}
          >
            {statuses.map((status) => (
              <SelectItem key={status.key}>{status.label}</SelectItem>
            ))}
          </Select>
          <Select
            className="sm:max-w-xs w-full"
            // label="Filter by Status"
            placeholder="Select phase"
            defaultSelectedKeys={['all']}
            selectedKeys={[phaseFilter]}
            startContent={'Phase:'}
            onChange={(e) => setPhaseFilter(e.target.value)}
          >
            {phases.map((stage) => (
              <SelectItem key={stage.key}>{stage.label}</SelectItem>
            ))}
          </Select>
          <Select
            className="sm:max-w-xs w-full"
            defaultSelectedKeys={['all']}
            items={locations}
            selectedKeys={[locationFilter]}
            startContent={'Location:'}
            onChange={(e) => setLocationFilter(e.target.value)}
          >
            {locations.map((city) => (
              <SelectItem key={city.key}>{city.label}</SelectItem>
            ))}
          </Select>

          {session?.user.role !== 'admin' && (
            <div className="sm:max-w-xs w-full">
              {' '}
              <ButtonGroup>
                {OPERATIONS_TABS.map((filter) => (
                  <Button
                    key={filter.value}
                    variant={operationsTab === filter.value ? 'solid' : 'flat'}
                    className={
                      operationsTab === filter.value
                        ? 'bg-[#F19645] text-white font-semibold'
                        : ''
                    }
                    onPress={() => setOperationsTab(filter.value)}
                  >
                    {filter.label}
                  </Button>
                ))}
              </ButtonGroup>
            </div>
          )}
        </div>
        {session?.user.role === 'supervisor' && <CreateProjectForm />}
      </div>

      {/* Operations table  */}
      <OperationsTable
        projects={projects}
        handleSort={handleSort}
        isLoading={isLoading}
        search={search}
        setSearch={setSearch}
        page={page}
        totalPages={totalPages}
        setPage={setPage}
        operationsTab={operationsTab}
      />
    </section>
  );
};

export default OperationsDashboard;
