'use client';
import React from 'react';
import DashboardHeader from '../DashboardHeader';
import {
  ArrowTrendingUpIcon,
  ArrowUpIcon,
  CheckCircleIcon,
  FolderOpenIcon,
  UsersIcon,
} from '@heroicons/react/24/outline';
import AnalyticsCard from '@/components/Cards/Dashboard/AnalyticsCard';
import LineChart from '@/components/Charts/LineChart';
import BarChart from '@/components/Charts/BarChart';
import DonutChart from '@/components/Charts/DonutChart';
import ChartFilterToggle from '@/components/Charts/ChartFilterToggle';
import { ChartFilter } from '@/types';
import { Select, SelectItem } from '@heroui/select';

const DashboardOverview = () => {
  const [filter, setFilter] = React.useState<ChartFilter>('week');
  const seriesLine = [
    {
      name: 'Projects Completed',
      data: [2, 4, 6, 8, 12, 15, 18, 20, 22, 25, 28, 30],
    },
  ];
  const seriesBar = [
    {
      name: 'Projects Completed',
      data: [2, 4, 6, 8, 12, 15],
    },
  ];
  const analyticsData = [
    {
      value: `1.26k total projects`,
      icon: <FolderOpenIcon className="h-6 w-6 text-orange-400" />,
      descriptionIcon: <ArrowUpIcon className="h-3 w-3 text-green-400" />,
      descriptionText: '5% increase from last week',
    },
    {
      value: `1.11k completed projects`,
      icon: <CheckCircleIcon className="h-6 w-6 text-orange-400" />,
      descriptionIcon: <ArrowUpIcon className="h-3 w-3 text-green-400" />,
      descriptionText: '12% increase from last month',
    },
    {
      value: `₦500M revenue`,
      icon: <ArrowTrendingUpIcon className="h-6 w-6 text-orange-400" />,
      descriptionIcon: <ArrowUpIcon className="h-3 w-3 text-green-400" />,
      descriptionText: ' 8% increase from last quarter',
    },
    {
      value: `145 clients`,
      icon: <UsersIcon className="h-6 w-6 text-orange-400" />,
      descriptionIcon: <ArrowUpIcon className="h-3 w-3 text-green-400" />,
      descriptionText: '15% increase from last quarter',
    },
  ];
  return (
    <section className="flex flex-col gap-4">
      <DashboardHeader
        title="Dashboard Overview"
        description="Welcome to your dashboard overview. Here you can see an overview of your project's performance and recent activity."
      />
      {/* Analytics Card */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {analyticsData.map((data, index) => (
          <AnalyticsCard key={index} data={data} />
        ))}
      </div>
      {/*  Project Performance Charts  */}
      <div className="flex sm:flex-row flex-col gap-4">
        <div className="bg-white dark:bg-transparent dark:text-white rounded-lg h-[550px] dark:p-0 p-4 w-full">
          <div>
            <DashboardHeader
              title="Project Performance"
              description="Track the performance of your projects over time with our interactive line chart."
            />
            {/* chart filter  */}
            <div className="w-full flex justify-end">
              <ChartFilterToggle value={filter} onChange={setFilter} />
            </div>
          </div>
          <div className=" dark:text-black mt-6">
            {/* Chart  */}
            <LineChart series={seriesLine} />
          </div>
        </div>
        <div className="bg-white  dark:bg-transparent dark:text-white rounded-lg sm:h-[550px] h-[580px] dark:p-0 p-4 w-full">
          <div>
            <DashboardHeader
              title="Revenue by service"
              description="Track revenue generated by different services over time."
            />
          </div>
          <div className="w-full flex justify-end">
            {' '}
            <Select
              className="w-40"
              aria-label="Revenue filter"
              labelPlacement="outside"
              name="revenue-filter"
              placeholder="Filter by"
            >
              <SelectItem key="4">First Quarter</SelectItem>
              <SelectItem key="8">Second Quarter</SelectItem>
              <SelectItem key="12">Third Quarter</SelectItem>
            </Select>
          </div>
          <div className="mb-4 dark:text-black">
            {/* BarChart  */}
            <BarChart series={seriesBar} />
          </div>
        </div>
      </div>
      {/*  Task & Lead Charts  */}
      <div className="flex sm:flex-row flex-col gap-4">
        <div className="bg-white dark:bg-transparent dark:text-white rounded-lg sm:h-[500px] dark:p-0 p-4 w-full">
          <div>
            <DashboardHeader title="Task Overview" description="" />
          </div>
          <div className="mb-4  dark:text-black">
            {/* Chart  */}
            <DonutChart
              series={[44, 55, 41, 17, 15]}
              labels={[
                'To do',
                'In progress',
                'Complete',
                'On hold',
                'Cancelled',
              ]}
              colors={['#f97316', '#22c55e', '#3b82f6', '#ef4444', '#8b5cf6']}
            />
          </div>
        </div>
        <div className="bg-white dark:bg-transparent dark:text-white rounded-lg sm:h-[500px] dark:p-0 p-4 w-full">
          <div>
            <DashboardHeader title="Lead Sources" description="" />
          </div>
          <div className="mb-4  dark:text-black">
            {/* Chart  */}
            <DonutChart
              series={[44, 55, 41, 17, 15]}
              labels={['Instagram', 'Referrals', 'Website', 'Others']}
              colors={['#000000', '#1f1f1f', '#3f3f46', '#52525b', '#71717a']}
            />
          </div>
        </div>
      </div>
    </section>
  );
};

export default DashboardOverview;
